### PR TITLE
Add pre-commit-config.yml

### PR DESCRIPTION
**Pull request by jstockwin**
See https://pre-commit.com/ for more details. You can now run `pre-commit install` (after a `pip install pre-commit`) and then every time you commit it'll check the lining automatically. It only runs on the files you've changed, so is pretty quick.

I also realised we weren't properly running isort anywhere, so I fixed that.

### CODE REVIEW

**Review by paulopaixaoamaral — APPROVED** [review]
LGTM

I wonder if going forward we should consider not running the linting in the CI and run it only in the pre-commit hooks, since currently we have 2 different ways of doing linting in the project. 
We would just need to add `flake8` (since `pycodestyle` does not have pre-commit hooks, but it would pretty much do the same and a few more things: https://pypi.org/project/flake8) and `pytype` to the pre-commit hooks.

**Comment by jstockwin** [comment]
@paulopaixaoamaral agreed it would be nice to have one way of doing it. That said, I don't think we can just not run it in CI - you need to install the pre-commit hooks. If someone hasn't done this, they'll be able to commit changes that would fail linting etc.

That said, we can probably just validate that the hooks pass on all files in CI, rather than explicitly running everything.

I'll leave this open for now and look into it.

**Comment by jstockwin** [comment]
I think we should use https://pre-commit.ci/, which basically does what we needs, even does some updates for us, and is free for open source

**Comment by jstockwin** [comment]
I _think_ I've installed the pre-commit checker... but it's trying to run against master for now. I am going to merge this and see how it goes - we can always fix it later.

**Comment by jstockwin** [comment]
Additional stuff is being done here: https://github.com/jstockwin/py-pdf-parser/pull/292

**Pull request merged**
