### PR TITLE
Add custom filter predicate and header/footer filters

### LINKED ISSUE #384: Add custom filter predicate and header/footer filters
**Feature Request - methods to add to ElementList**

```py
# Filter elements based on a custom filter passed into the method
ElementList.filter(predicate: Callable[[PDFElement], bool]) -> ElementList

# Filter elements based on font size alone, ignoring differences in font
ElementList.filter_by_font_size(font_size: float) -> ElementList

# Filter out elements that are contained within the page header
ElementList.filter_out_header(bottom_of_header_y: float) -> ElementList

# Filter out elements that are contained within the page footer
ElementList.filter_out_footer(top_of_footer_y: float) -> ElementList

# Return the first element in the ElementList
ElementList.first() -> PDFElement

# Return the last element in the ElementList
ElementList.last() -> PDFElement
```

I'd be happy to implement these myself

### PR DESCRIPTION
**Pull request by aiden2480**
**Description**

Implement methods from #384

**Linked issues**

Closes #384

**Testing**

Unit tests have been added

**Checklist**

- [x] I have provided a good description of the change above
- [x] I have added any necessary tests
- [x] I have added all necessary type hints
- [x] I have checked my linting (`docker-compose run --rm lint`)
- [x] I have added/updated all necessary documentation
- [x] I have updated `CHANGELOG.md`, following the format from
      [Keep a Changelog](https://keepachangelog.com/en/1.0.0/).

### CODE REVIEW

**Comment by jstockwin** [comment]
@aiden2480 thanks for submitting a PR (and for highlighting some issues).

Apologies for not getting back to you sooner. This is on my list, and I'll try to find time to look in more detail when I can.

**Review by jstockwin — APPROVED** [review]
This looks really nice - thanks. I like the `.filter` method - it really cleans up a lot of the other code, and is a nice all-purpose solution.

**Comment by aiden2480** [comment]
Thanks for reviewing, and maintaining this library. Would love to see this released to PyPi if possible

**Comment by jstockwin** [comment]
@aiden2480 this is now released to PyPi in 0.13.0 (thanks for @paulopaixaoamaral for doing the release!)

**Pull request merged**
